### ISSUE TITLE
Potential idea to increase efficiency for this problem (Enhancement)

### ISSUE THREAD

**Issue by ghost** [MatthewDaws/AccessibleLaTeX#1]
At that point, instead of working directly from LaTeX to HTML wouldn't it just be easier to use [org-mode](https://orgmode.org/) inside Emacs? org-mode allows your whole workflow to be written in Markdown and allows for swift exporting to LaTeX and HTML. Which, in my eyes. Allows for highly efficient writing as well as directly reading from the source file.

**Comment by MatthewDaws** [comment]
Thanks for the thought Michael!  My aim for this mini-site is to be a resource for myself, and _also_ for colleagues who are almost certainly less technically adept.  Mentioning "emacs" in this context is likely not useful.

The main problem is the _huge_ amount of material we already have in LaTeX.  For reasons I'll explain later in the site, there is also the issue that for 99% of our students, what we currently do will probably continue to be the most useful.  My first aim is to simply find a quick way to get that legacy material into a more accessible format.

That being said, looking at the internal structure of some of the lecture notes I have inherited, and as I read more, perhaps "throwing it all away and starting again" isn't such a bad option.  [Bookdown](https://bookdown.org/) might be useful in this direction (though it would be nice to not leave the Python world...)

**Comment by ghost** [comment]
Yes indeed you have highlighted the issue very clearly, to get improved efficiency you have to put the initial work in. I remember spending a week or two just getting automatic citations to convert from .org to html and latex and that was a nightmare, especially when balancing daily duties. 

It's certainly difficult to get undergraduates to do something that - although would be more beneficial to them in the future - *doesn't just work*. Also, especially for collaboration there would be issues. Although you can write in markdown and then convert it to LaTeX for the collaborator, it is significantly more stressful to convert back from LaTeX. This clearly separates workflow mentality, which is less efficient. 

I would think starting again would be a good idea, but that's only because I've been your tufte-style lecture notes. Which I feel are the best layout for knowledge presenting and acquisition... if only I was design-savvy enough in LaTeX to make a tufte-thesis layout that also conformed with strict university policy.

I'll keep updated with your sites updates too, I can also email you an example of org-mode in action if you are interested. I've made posters, presentations and my 1st year Confirmation Review in org-mode and the benefits significantly outweigh the initial time investment.

R isn't too far from Python though, I've been independently making project in Rust. Which has been rather hellish. I'm bringing myself back to Python to do some personal simulations and I just love how in Python everything just *works*

**Comment by ghost** [comment]
Closing because I was assuming accessibility was more on the teaching student side

This issue has no significant relevence to conforming to the uni reg.
